
### Get's all the movies.
GET http://localhost:3000/movies


### Get's a movie by it's id
GET http://localhost:3000/movies/65c3db81c06eea3195b6515d


### Creates a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Harry Potter",
  "genre": "Fantasy",
  "releaseDate": "2000-12-13",
  "viewerDiscretion": "PG 13",
  "productionCompany": "Warner Bros",
  "director": "Jk Rowlin",
  "duration": "122m",
  "language": "English",
  "boxOffice": 879334678
}