
### Get's all the movies.
GET http://localhost:3000/movies


### Get's a movie by it's id
GET http://localhost:3000/movies/title


### Creates a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Doctor Strange in the Multiverse of Madness",
  "genre": "Superhero",
  "releaseDate": "2022-05-02",
  "viewerDiscretion": "PG 13",
  "productionCompany": "Marvel Studios",
  "director": "Sam Raimi",
  "duration": "126m",
  "language": "English",
  "boxOffice": 955800000
}