
### This is the movies rest file
### Get's all the movies.
GET http://localhost:3000/movies


### Get's a movie by it's title
GET http://localhost:3000/movies/leg


### Creates a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Amistad",
    "genre": "Horror/Mystery",
    "releaseDate": "1997-12-10T00:00:00.000Z",
    "viewerDiscretion": "R",
    "productionCompany": "DreamWorks Pictures",
    "directors": "Steven Spillberg/David Franzoni",
    "duration": "154m",
    "language": "English",
    "boxOffice": 58300000
}


### This is our put request.
PUT http://localhost:3000/movies/65c4ec2a769bc49c2747fb14
Content-Type: application/json

{
  "title": "Venom",
  "genre": "Action/Sci-fi",
  "releaseDate": "2018-10-01",
  "viewerDiscretion": "16",
  "productionCompany": "The Imaginarium",
  "directors": "Ruben Fleischer",
  "duration": "112m",
  "language": "English",
  "boxOffice": 856100000
}

### 
DELETE http://localhost:3000/movies/65c4ec2a769bc49c2747fb14


